services:
  sstpc:
    build: .
    container_name: sstpc
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    privileged: true
    devices:
      - /dev/ppp:/dev/ppp
    ports:
      - ${PORT:-8080}:${PORT:-8080}
    environment:
      REMOTEHOST: ${REMOTEHOST}
      SSTP_USER: ${SSTP_USER}
      SSTP_PASSWORD: ${SSTP_PASSWORD}
    volumes:
      - ./certs:/certs:ro

  # app:
  #   image: xxx/xxx
  #   restart: unless-stopped
  #   network_mode: "service:sstpc"
